spring:
  shardingsphere:
    datasource:
      names: master,master1 #,slave,
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.1.120:3306/dian?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=false
        username: root
        password: root
      master1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.1.202:3306/hbhs?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=false
        username: root
        password: root
#      slave:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://192.168.1.120:3307/dian?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=false
#        username: root
#        password: root
    sharding:
      default-database-strategy:
        hint:
          algorithm-class-name: com.shardingsphere.demo.hint.MatchHintShardingAlgorithm
#      master-slave-rules:
#        master0:
#          load-balance-algorithm-type: random
#          master-data-source-name: master
#          slave-data-source-names: slave
    props:
      sql:
        show: true
mybatis:
  config-location: classpath:mybatis-config.xml

